baseURL = "https://guixcn.github.io/"
title = "Guix"
theme = "hugo-notepadium"
copyright = "© 2019-2021 Guix China Community"

disableHugoGeneratorInject = true
languageCode = "zh-cn"
hasCJKLanguage = true

[menu]
  [[menu.main]]
    url = "/"
    name = "首页"
    weight = 1

  [[menu.main]]
    url = "/about/"
    name = "简介"
    weight = 1

  [[menu.main]]
    url = "/contact/"
    name = "联系我们"
    weight = 1

  [[menu.main]]
    url = "/blog/"
    name = "文章"
    weight = 1

  [[menu.footer1]]
    url = "/"
    name = "首页"
    weight = 1

[params]
    style = "auto"  # default: auto. light: light theme, dark: dark theme, auto: based on system.
    logo = "/images/guix-logo.svg"
    slogan = "自由而不是白嫖"
    beian = "鄂ICP备20009141号-1"

[params.syntax]
    use = "prismjs"  # builtin: "prismjs", "hljs". "none" means Chroma
    theme = "dracula"
    darkTheme = "dark"

[params.nav]
    showCategories = false
    showTags = false

[[params.nav.custom]]
    title = "简介"
    url = "/about/"

[[params.nav.custom]]
    title = "联系我们"
    url = "/contact/"

[[params.nav.custom]]
    title = "捐赠"
    url = "/donate/"

[[params.nav.custom]]
    title = "Free Shell"
    url = "/free-shell/"

[[params.nav.custom]]
    title = "Wiki"
    url = "/wiki/"

[[params.nav.custom]]
    title = "文章"
    url = "/blog/"
